---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-sample-data
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ingest-sample-data
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: ingest-sample-data
        image: ghcr.io/kusaridev/local-organic-guac@sha256:4ceb73778530d652755777c6e81de6994f7f94e103ee4a3ff55b797e813ac646
        command: ['sh', '-c', '/tmp/guac/ingest-sample-data.sh']
        workingDir: /guac
        ports:
          - containerPort: 2782
        volumeMounts:
          - name: guac-config
            mountPath: /guac
            readOnly: true
          - name: ingest-sample-data
            mountPath: /tmp/guac
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: imagepullsecret
      volumes:
        - name: guac-config
          configMap:
            name: guac-cm
        - name: ingest-sample-data
          configMap:
            name: ingest-sample-data
            defaultMode: 0755

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-sample-data
data:
  ingest-sample-data.sh: |
    #!/usr/bin/env bash
    set -e
    
    apt-get update && apt-get install -y git

    export GUACSEC_HOME="/guac"
    cd ${GUACSEC_HOME}
    git clone https://github.com/guacsec/guac-data.git /tmp/guac-data
    /opt/guac/guacone files /tmp/guac-data/docs
    /opt/guac/guacone files /tmp/guac-data/top-dh-sboms
    /opt/guac/guacone files /tmp/guac-data/some-sboms